- name: Instalar OBS
  flatpak:
    name: com.obsproject.Studio
    state: present
    remote: flathub

- name: Instalar Stremio
  flatpak:
    name:
      - com.stremio.Stremio
      - com.stremio.Service
    state: present
    remote: flathub
