- name: Instalar Zsh
  become: true
  dnf:
    name: zsh
    state: present

- name: Definir Zsh como shell padrão do usuário {{ desktop_user }}
  become: true
  user:
    name: "{{ desktop_user }}"
    shell: /bin/zsh

- name: Instalar Oh My Zsh de forma não interativa
  become: false
  become_user: "{{ desktop_user }}"
  shell: |
    export RUNZSH=no
    export CHSH=no
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o /tmp/ohmyzsh-install.sh
    sh /tmp/ohmyzsh-install.sh
  args:
    creates: /home/{{ desktop_user }}/.oh-my-zsh

- name: Baixar arquivo do repositório LazyGit
  become: true
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/dejan/lazygit/repo/fedora-{{ ansible_facts.distribution_major_version }}/dejan-lazygit-fedora-{{ ansible_facts.distribution_major_version }}.repo
    dest: /etc/yum.repos.d/dejan-lazygit.repo
    mode: '0644'
    force: no

- name: Instalar Lazygit
  become: true
  dnf:
    name: lazygit
    state: present

- name: Instalar dependências LunarVim
  become: true
  dnf:
    name:
      - git
      - make
      - neovim
      - python3-pip
      - python3
      - npm
      - nodejs
      - cargo
      - ripgrep
    state: present

- name: Instalar plugin neovim para Node.js (npm global)
  become: true
  npm:
    name: neovim
    global: yes

- name: Instalar LunarVim de forma não interativa
  become: false
  become_user: "{{ desktop_user }}"
  shell: |
    export LV_BRANCH='release-1.4/neovim-0.9'
    bash <(curl -fsSL https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh) -y --install-dependencies
  args:
    creates: /home/{{ desktop_user }}/.local/share/lunarvim
  ignore_errors: true

- name: Sincronizar plugins do LunarVim
  become: false
  become_user: "{{ desktop_user }}"
  shell: |
    /home/{{ desktop_user }}/.local/bin/lvim --headless "+Lazy! sync" +qall

- name: Instalar Podman
  flatpak:
    name: io.podman_desktop.PodmanDesktop
    state: present
    remote: flathub
