- name: Obter a URL da última release do lsfg-vk
  uri:
    url: https://api.github.com/repos/PancakeTAS/lsfg-vk/releases/latest
    return_content: yes
  register: lsfg_release

- name: Extrair URL do RPM x86_64
  set_fact:
    lsfg_rpm_url: "{{ (lsfg_release.json.assets | selectattr('name','match','lsfg-vk-.*\\.x86_64\\.rpm') | list)[0].browser_download_url }}"

- name: Baixar o RPM do lsfg-vk
  get_url:
    url: "{{ lsfg_rpm_url }}"
    dest: "/tmp/{{ lsfg_rpm_url | basename }}"
    mode: '0644'

- name: Instalar o lsfg-vk
  dnf:
    name: "/tmp/{{ lsfg_rpm_url | basename }}"
    state: present
    disable_gpg_check: yes

- name: Instalar Discord
  flatpak:
    name: com.discordapp.Discord
    state: present
    remote: flathub

- name: Obter a URL da última release do Heroic
  uri:
    url: https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest
    return_content: yes
  register: heroic_release

- name: Extrair URL do RPM x86_64
  set_fact:
    heroic_rpm_url: "{{ (heroic_release.json.assets | selectattr('name','match','Heroic-.*-linux-x86_64\\.rpm') | list)[0].browser_download_url }}"

- name: Baixar o RPM do Heroic
  get_url:
    url: "{{ heroic_rpm_url }}"
    dest: "/tmp/{{ heroic_rpm_url | basename }}"
    mode: '0644'

- name: Instalar o Heroic
  dnf:
    name: "/tmp/{{ heroic_rpm_url | basename }}"
    state: present
    disable_gpg_check: yes

- name: Obter a URL da última release do Hydra
  uri:
    url: https://api.github.com/repos/hydralauncher/hydra/releases/latest
    return_content: yes
  register: hydra_release

- name: Extrair URL do RPM x86_64
  set_fact:
    hydra_rpm_url: "{{ (hydra_release.json.assets | selectattr('name','match','hydralauncher-.*x86_64\\.rpm') | list)[0].browser_download_url }}"

- name: Baixar o RPM do Hydra
  get_url:
    url: "{{ hydra_rpm_url }}"
    dest: "/tmp/{{ hydra_rpm_url | basename }}"
    mode: '0644'

- name: Instalar o Hydra
  dnf:
    name: "/tmp/{{ hydra_rpm_url | basename }}"
    state: present
    disable_gpg_check: yes

- name: Obter versão do Fedora
  command: rpm -E %fedora
  register: fedora_version
  changed_when: false

- name: Instalar RPM Fusion Free e Non-Free
  become: true
  shell: >
    dnf install -y
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm
  args:
    creates: /etc/yum.repos.d/rpmfusion-free.repo

- name: Habilitar fedora-cisco-openh264 se não estiver habilitado
  become: true
  command: dnf config-manager --setopt=fedora-cisco-openh264.enabled=1
  args:
    creates: /etc/dnf/dnf.conf
  register: enable_openh264
  failed_when: false

- name: Instalar Steam
  dnf:
    name: steam
    state: present
