- name: Instalar Remmina
  flatpak:
    name: org.remmina.Remmina
    state: present
    remote: flathub

- name: Instalar Microsoft Teams
  flatpak:
    name: com.github.IsmaelMartinez.teams_for_linux
    state: present
    remote: flathub

- name: Instalar Thunderbird
  flatpak:
    name: org.mozilla.Thunderbird
    state: present
    remote: flathub
